language: node_js
sudo: required
services:
  - docker
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
  - sudo docker-compose -f ./docker/docker-compose.yml up -d
script:
  - npm run lint
  - npm run start:ci
  - npm run test
after_script:
  - greenkeeper-lockfile-upload
deploy:
  provider: heroku
  app: karbon14-home-api
  api_key: 
    secure: $HEROKU_API_KEY