language: node_js
sudo: required
services:
  - docker
before_install:
  - npm install -g greenkeeper-lockfile@1
  - npm install -g codecov
before_script:
  - greenkeeper-lockfile-update
  - sudo docker-compose -f ./docker/docker-compose.yml up -d
script:
  - npm run lint
  - npm run start:ci
  - npm run test
  - npm run codecov
after_script:
  - greenkeeper-lockfile-upload
deploy:
  - provider: s3
    acl: public_read
    local_dir: 'dist'
    skip_cleanup: true
    bucket: karbon14-home
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    on:
      branch: master