version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/karbon14-home
    owner: root
hooks:
  Install:
    - location: scripts/npm-install.sh
      runas: root
      timeout: 300
  AfterInstall:
    - location: scripts/npm-start.sh
      runas: root
      timeout: 60