version: '3'

services:
  nginx:
    image: "nginx"
    container_name: "nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    links:
      - karbon14-api
      - swagger_ui
    depends_on:
      - karbon14-api
      - swagger_ui
    
  swagger_ui:
    image: "swaggerapi/swagger-ui"
    environment:
      - API_URL=https://api.karbon14.org/v1/swagger.json
    restart: always

  karbon14-api:
     build:
       context: ..
       dockerfile: ./docker/karbon14-api.dockerfile
     container_name: "karbon14-api"
     restart: always
     environment:
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - EMAIL_CONTACT_TO=${EMAIL_CONTACT_TO}
      - MAILCHIMP_API_KEY=${MAILCHIMP_API_KEY}
      - MAILCHIMP_LIST_ID=${MAILCHIMP_LIST_ID}
      - WHITEPAPER_FILE_EN=${WHITEPAPER_FILE_EN}
      - WHITEPAPER_FILE_ES=${WHITEPAPER_FILE_ES}


